name: deploy.yml
on:
  push:
    tags: v*
jobs:
  test-app:
    runs-on: ubuntu-latest
    env:
      CHATTER_DATABASE_URL: ${{ secrets.CHATTER_DATABASE_URL }}
      ENV: ${{ secrets.ENV }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Build & Execute
        run: |
          echo "CHATTER_DATABASE_URL=${CHATTER_DATABASE_URL}" > .env
          echo "ENV=${ENV}" >> .env
          docker compose up -d --build
      - name: Install Dependencies
        run: go mod tidy



      - name: Run Unit Tests
        run: pytest -v ./test/test.py
  deploy:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
  release:
    needs: [ test-app, deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}